### ISSUE TITLE
Not what I expected

### ISSUE THREAD

**Issue by jdhenckel** [theonlylawislove/DCMTK.NET#1]
I was hoping that this would call Dcmtk, findscu directly using pinvoke. Instead it runs it as a command line EXE and captures stdout.  A better way would be to modify the source of dcmtk, recompile as a DLL, and write your own DcmFindSCUCallback implementation to get result.

**Comment by theonlylawislove** [comment]
Check out the CLI branch. That is where most of my work is. Ignore the CLI stuff. I have to remove that stuff. Super old.

https://github.com/theonlylawislove/DCMTK.NET/tree/cli

**Comment by jdhenckel** [comment]
Thanks!  that's much better. I tried to compile with 2013 and net 4.5. at first I got a ton of warnings. But then I restarted, clean, recompile, and now it seems to be working!!  This will save me a lot of work on my project. Can I have permission to use this for an internal app at Mayo Clinic? All I need is to call findscu from C# to get a list of patients and studies in MWL for a given date.

**Comment by theonlylawislove** [comment]
All yours.
